#@ load("@ytt:data", "data")
#@ load("metadata.lib.yaml", "metadata")
#@ load("labels.lib.yaml", "labels")
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: #@ metadata(data.values.alertmanagerName, data.values.namespace, app=data.values.alertmanagerName, comp=data.values.alertmanagerComponent, ver=data.values.alertmanagerVersion)
spec:
  maxUnavailable: 1
  selector:
    matchLabels: #@ labels(app=data.values.alertmanagerName, comp=data.values.alertmanagerComponent)
