#@ load("@ytt:data", "data")
#@ load("metadata.lib.yaml", "metadata")
#@ load("labels.lib.yaml", "labels")
---
apiVersion: v1
kind: Service
metadata: #@ metadata(data.values.alertmanagerName, data.values.namespace, app=data.values.alertmanagerName, comp=data.values.alertmanagerComponent, ver=data.values.alertmanagerVersion)
spec:
  ports:
  - name: web
    port: 9093
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector: #@ labels(data.values.alertmanagerName, data.values.alertmanagerComponent)
  sessionAffinity: ClientIP
