#@ load("@ytt:data", "data")
#@ load("metadata.lib.yaml", "metadata")
#@ load("labels.lib.yaml", "labels")
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels: #@ labels(data.values.promAdapterName, data.values.promAdapterComponent, version=data.values.promAdapterVersion)
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: #@ data.values.promAdapterName
    namespace: #@ data.values.namespace
  version: v1beta1
  versionPriority: 100
