#@ load("@ytt:data", "data")
#@ load("metadata.lib.yaml", "metadata")
#@ load("labels.lib.yaml", "labels")
---
apiVersion: v1
kind: Service
metadata: #@ metadata(data.values.promAdapterName, data.values.namespace, app=data.values.promAdapterName, comp=data.values.promAdapterComponent, ver=data.values.promAdapterVersion)
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector: #@ labels(data.values.promAdapterName, data.values.promAdapterComponent)
