#@ load("@ytt:data", "data")
#@ load("metadata.lib.yaml", "metadata")
#@ load("labels.lib.yaml", "labels")
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: #@ metadata(data.values.prometheusInstance, data.values.namespace, app=data.values.prometheusName, comp=data.values.prometheusComponent, ins=data.values.prometheusInstance, ver=data.values.prometh    eusVersion)
spec:
  endpoints:
  - interval: 30s
    port: web
  - interval: 30s
    port: reloader-web
  selector:
    matchLabels: #@ labels(data.values.prometheusName, component=data.values.prometheusComponent, instance=data.values.prometheusInstance)
