#@ load("@ytt:data", "data")
#@ load("metadata.lib.yaml", "metadata")
#@ load("labels.lib.yaml", "labels")
---
apiVersion: v1
kind: Service
metadata: #@ metadata(data.values.prometheusInstance, data.values.namespace, app=data.values.prometheusName, comp=data.values.prometheusComponent, ins=data.values.prometheusInstance, ver=data.values.prometheusVersion)
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector: #@ labels(data.values.prometheusName, component=data.values.prometheusComponent, instance=data.values.prometheusInstance)
  sessionAffinity: ClientIP
