#@ load("@ytt:data", "data")
#@ load("labels.lib.yaml", "labels")
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: #@ data.values.grafanaName+"-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
