#@ load("@ytt:data", "data")
#@ load("/1-libs/metadata.lib.yaml", "metadata")
#@ load("/1-libs/labels.lib.yaml", "labels")
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: #@ metadata(data.values.alertmanagerName, app=data.values.alertmanagerName, comp=data.values.alertmanagerComponent, ns=data.values.namespace, ver=data.values.alertmanagerVersion)
spec:
  endpoints:
  - interval: 30s
    port: web
  - interval: 30s
    port: reloader-web
  selector:
    matchLabels: #@ labels(app=data.values.alertmanagerName, comp=data.values.alertmanagerComponent)
