#@ load("@ytt:data", "data")
#@ load("/1-libs/metadata.lib.yaml", "metadata")
#@ load("/1-libs/labels.lib.yaml", "labels")
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata: #@ metadata(data.values.prometheusInstance, app=data.values.prometheusName, ins=data.values.prometheusInstance, comp=data.values.prometheusName, ns=data.values.namespace, ver=data.values.prometheusVersion)
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: #@ data.values.alertmanagerName
      namespace: #@ data.values.namespace
      port: web
  enableFeatures: []
  externalLabels: {}
  image: quay.io/prometheus/prometheus:v2.32.1
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels: #@ labels(data.values.prometheusName, data.values.prometheusComponent, ins=data.values.prometheusInstance, ver=data.values.prometheusVersion)
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleNamespaceSelector: {}
  ruleSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: #@ data.values.prometheusSA
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: #@ data.values.prometheusVersion
