#@ load("@ytt:data", "data")
#@ load("/1-libs/metadata.lib.yaml", "metadata")
#@ load("/1-libs/labels.lib.yaml", "labels")
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: #@ metadata(data.values.prometheusInstance, app=data.values.prometheusName, ins=data.values.prometheusInstance, comp=data.values.prometheusName, ns=data.values.namespace, ver=data.values.prometheusVersion)
spec:
  minAvailable: 1
  selector:
    matchLabels: #@ labels(data.values.prometheusName, data.values.prometheusComponent, ins=data.values.prometheusInstance)
