#@ load("@ytt:data", "data")
#@ load("metadata.lib.yaml", "metadata")
#@ load("labels.lib.yaml", "labels")
---
apiVersion: v1
kind: Service
metadata: #@ metadata(data.values.blackboxExporterName, data.values.namespace, app=data.values.blackboxExporterName, comp=data.values.blackboxExporterComponent, ver=data.values.blackboxExporterVersion)
spec:
  ports:
  - name: https
    port: 9115
    targetPort: https
  - name: probe
    port: 19115
    targetPort: http
  selector: #@ labels(data.values.blackboxExporterName, data.values.blackboxExporterComponent)
