#@ load("@ytt:data", "data")
#@ load("/1-libs/metadata.lib.yaml", "metadata")
---
apiVersion: v1
kind: Secret
metadata: #@ metadata(data.values.grafanaName+"-config", app=data.values.grafanaName, comp=data.values.grafanaComponent, ns=data.values.namespace, ver=data.values.grafanaVersion)
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC
type: Opaque
