#@ load("@ytt:data", "data")
#@ load("/1-libs/metadata.lib.yaml", "metadata")
#@ load("/1-libs/labels.lib.yaml", "labels")
---
apiVersion: v1
kind: ServiceMonitor
metadata: #@ metadata(data.values.grafanaName, app=data.values.grafanaName, comp=data.values.grafanaComponent, ns=data.values.namespace, ver=data.values.grafanaVersion)
spec:
  endpoints:
  - interval: 15s
    port: http
  selector:
    matchLabels: #@ labels(app=data.values.grafanaName, comp=data.values.grafanaComponent)
